version: '3.9'

services:
  php-apache:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
